### ISSUE TITLE
Delete operations are not sent correctly in Kafka

### ISSUE THREAD

**Issue by dancb10** [scylladb/scylla-cdc-source-connector#60]
I've been playing with this connector for sending data from ScyllaDB -> Kafka -> ElasticSearch.
I'm trying to use a unique document ID which i am able to set from scyllaDB and not allow the ElasticSearch connector to generate a unique ID per document id.

When ingesting data using the CDC ScyllaDB connector i use the following configuration
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: scylladb-connector
  labels:
    strimzi.io/cluster: scylla-to-elasticsearch
spec:
  class: com.scylladb.cdc.debezium.connector.ScyllaConnector
  tasksMax: 1
  config:
    scylla.name: test
    scylla.cluster.ip.addresses: scylla-client.scylla.svc.cluster.local:9042
    scylla.table.names: messages
    auto.create.topics.enable: true
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
```

For the sake of having a better understanding I will paste the ElasticSearch Connector for pushing data to ES:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: elasticsearch-connector
  labels:
    strimzi.io/cluster: scylla-to-elasticsearch
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  tasksMax: 1
  config:
    topics: messages
    connection.url: https://quickstart-es-http.elastic-system.svc.cluster.local:9200
    connection.username: elastic
    connection.password: XXXX
    elastic.security.protocol: SSL
    elastic.https.ssl.keystore.location: /opt/kafka/security/keystore.jks
    elastic.https.ssl.keystore.password: "XXXX"
    elastic.https.ssl.truststore.location: /opt/kafka/security/truststore.jks
    elastic.https.ssl.truststore.password: "XXXX"
    key.ignore: false
    schema.ignore: true
    # Handle null values
    behavior.on.malformed.documents: ignore
    behavior.on.null.values: delete

    # Combine transformations into a single transforms field
    transforms: "FilterFields, FlattenStruct, TransformFields, LimitFields, InsertKey, ExtractId"

    # Specify the fields to exclude (source, before, ts_ms, transaction)
    transforms.FilterFields.type: org.apache.kafka.connect.transforms.ReplaceField$Value
    transforms.FilterFields.exclude: "source,before,ts_ms,transaction"

    # Flatten the Scylla CDC Kafka Messages
    transforms.FlattenStruct.type: org.apache.kafka.connect.transforms.Flatten$Value
    
    # Transform fields into direct values
    transforms.TransformFields.type: org.apache.kafka.connect.transforms.ReplaceField$Value
    transforms.TransformFields.renames: "after.dmid:dmid,after.edited.value: edited,after.message.value:message,after.messagetype:messagetype,after.mid:mid,after.replays.value:replays,after.uid:uid,after.id:id"

    transforms.LimitFields.type: org.apache.kafka.connect.transforms.ReplaceField$Value
    transforms.LimitFields.whitelist: "dmid,message,mid,uid,id"

    # `ValueToKey`: push an object of one of the column fields (`id`) into the key
    transforms.InsertKey.type: org.apache.kafka.connect.transforms.ValueToKey
    transforms.InsertKey.fields: id

    # `ExtractField`: convert key from an object to a plain field
    transforms.ExtractId.type: org.apache.kafka.connect.transforms.ExtractField$Key
    transforms.ExtractId.field: id
```

So basically I'm using one of my cluster keys as the unique ID within Elasticsearch. And everything works for CREATE and UPDATE operations. The problem is that when a DELETE operation is sent to Kafka, the ScyllaDB connector does not push a correct format. For example, even if within the CDC table i have the following info:

```
 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | attachments | cdc$deleted_attachments | cdc$deleted_edited | cdc$deleted_elements_attachments | cdc$deleted_elements_reactions | cdc$deleted_message | cdc$deleted_reactions | cdc$deleted_replays | cdc$end_of_batch | cdc$operation | cdc$ttl | dmid               | edited | id                                    | message              | messagetype | mid                | reactions | replays | uid
------------------------------------+--------------------------------------+------------------+-------------+-------------------------+--------------------+----------------------------------+--------------------------------+---------------------+-----------------------+---------------------+------------------+---------------+---------+--------------------+--------+---------------------------------------+----------------------+-------------+--------------------+-----------+---------+------------------------------
 0x517adf6a6ddb7ba7638ed4aa080026d1 | 9de5576c-bca6-11ef-7f4c-dcc6545c3cf6 |                0 |        null |                    True |               null |                             null |                           null |                null |                  True |                null |             True |             2 |    null | 537025661064198368 |  False | 537025661064198368-545144306059458769 |              YAYAYAA |     message | 545144306059458769 |      null |       0 | lECilNKQQAgyw60Iz101vR4AXEE3
 0x517adf6a6ddb7ba7638ed4aa080026d1 | d1392102-bca6-11ef-d8fe-0b070285f32e |                0 |        null |                    null |               null |                             null |                           null |                null |                  null |                null |             True |             1 |    null | 537025661064198368 |   True | 537025661064198368-545144306059458769 | pipipipipipIPIPIPIPI |     message | 545144306059458769 |      null |    null | lECilNKQQAgyw60Iz101vR4AXEE3
 0x517adf6a6ddb7ba7638ed4aa080026d1 | 065a29da-bca7-11ef-8d4d-83c4de8a989d |                0 |        null |                    null |               null |                             null |                           null |                null |                  null |                null |             True |             3 |    null | 537025661064198368 |   null | 537025661064198368-545144306059458769 |                 null |     message | 545144306059458769 |      null |    null | lECilNKQQAgyw60Iz101vR4AXEE3
```

Most important is the last operation which is the DELETE (3):
```
 0x517adf6a6ddb7ba7638ed4aa080026d1 | 065a29da-bca7-11ef-8d4d-83c4de8a989d |                0 |        null |                    null |               null |                             null |                           null |                null |                  null |                null |             True |             3 |    null | 537025661064198368 |   null | 537025661064198368-545144306059458769 |                 null |     message | 545144306059458769 |      null |    null | lECilNKQQAgyw60Iz101vR4AXEE3
```

As you can see I still have the ID correctly set within the column which I'm using as the document ID in Elasticsearch, 537025661064198368-545144306059458769 but when the message is sent to Kafka that message is basically null. Why is that and how can we use DELETES operations, I basically want to delete data from ElasticSearch (or at least invalidate) when there is a delete operation with my OWN unique id

**Comment by dancb10** [comment]
Basically the scenario is simple, I create a document with unique ID, I need that ID when I update the document or delete it. And while for updates everything is set correctly, for deletes it is failing since the ID is not present, the whole value of the message is null

**Comment by dancb10** [comment]
Hmmm if we were to do the transformations within the com.scylladb.cdc.debezium.connector.ScyllaConnector connector to basically set the kafka message id to payload.before.id (if this is a DELETE operation) or payload.after.id (if this is a CREATE or UPDATE) how would we do it? e.g.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: scylladb-connector
  labels:
    strimzi.io/cluster: scylla-to-elasticsearch
spec:
  class: com.scylladb.cdc.debezium.connector.ScyllaConnector
  tasksMax: 1
  config:
    scylla.name: famsocket
    scylla.cluster.ip.addresses: scylla-client.scylla.svc.cluster.local:9042
    scylla.table.names: personaldirectmessagemessages.messages
    auto.create.topics.enable: true
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true

    transforms: "ExtractId, InsertKey"

    # Extract 'id' from either 'before.id' or 'after.id' (depending on the CDC operation)
    transforms.ExtractId.type: org.apache.kafka.connect.transforms.ReplaceField$Value
    transforms.ExtractId.renames: "before.id:id,after.id:id"

    # Set the Kafka key to the 'id' field extracted in the previous transformation
    transforms.InsertKey.type: org.apache.kafka.connect.transforms.ValueToKey
    transforms.InsertKey.fields: id
```
Tried above but doesn't work
